### ISSUE TITLE
Gnome 46, Capslock+S brings up Quick Settings menu

### ISSUE THREAD

**Issue by jamespo** [lorens-osman-dev/lomotion#1]
For me on Gnome 46 / Arch, CapsLock+S brings up the Quick Settings menu (which is bound to Super+S by default) rather than next workspace

**Comment by lorens-osman-dev** [comment]
Temporary fix : 
- Open Settings > Keyboard > Keyboard Shortcuts > View and Customize Shortcuts
- Search "Quick Settings menu"
- Change the default Shortcuts
- Open Extensions Manger and disable Lomotion Extension then enable it

**Comment by jamespo** [comment]
Thanks, that seems to work. I didn't realise it disables the ctrl-alt-arrow workspace navigation however so it will take me some bedding in!

**Comment by lorens-osman-dev** [comment]
The extension was updated to address this issue
