### ISSUE TITLE
Extension unmaps compose key

### ISSUE THREAD

**Issue by Rafailek** [lorens-osman-dev/lomotion#2]
When the extension is enabled, it disables the compose key (found in settings under "Keyboard"). I usually have it set to Print Screen. I don't know if that behavior is intentional, but I find it inconvenient when I turn Lomotion off and on.

**Comment by lorens-osman-dev** [comment]
can you explain more , what compose key 😅 all what Lomotion do makes capslock key like super key then add 5 keybord shorcuts, in gnome 45 there was default shortcut (super+s) to show quick settings i disabled this shortcut that's all.

**Comment by Rafailek** [comment]
Sorry for taking long to reply!

I think that what happens is that because the feature I'm talking about is not enabled by default, it get disabled at some point for whatever reason. I think that it isn't that big a problem and isn't worth pursuing further.
